<?xml version="1.0" encoding="UTF-8" ?>
<project
    xmlns="http://maven.apache.org/POM/4.1.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.1.0 http://maven.apache.org/xsd/maven-4.1.0.xsd"
>
    <modelVersion>4.1.0</modelVersion>
    <groupId>cn.elvea.repo</groupId>
    <artifactId>parent</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>

    <!-- repository -->
    <repositories>
        <repository><!-- aliyun -->
            <id>aliyun-public</id>
            <url>https://maven.aliyun.com/repository/public</url>
        </repository>
        <repository><!-- spring -->
            <id>aliyun-spring</id>
            <url>https://maven.aliyun.com/repository/spring</url>
        </repository>
    </repositories>
    <pluginRepositories>
        <pluginRepository><!-- aliyun -->
            <id>aliyun-public</id>
            <url>https://maven.aliyun.com/repository/public</url>
        </pluginRepository>
        <pluginRepository><!-- spring -->
            <id>aliyun-spring</id>
            <url>https://maven.aliyun.com/repository/spring</url>
        </pluginRepository>
    </pluginRepositories>

    <properties>
        <!-- project -->
        <project.source>25</project.source>
        <project.target>25</project.target>
        <project.encoding>UTF-8</project.encoding>
        <project.build.version>1.0.0</project.build.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <!-- spring -->
        <spring-ai.version>2.0.0</spring-ai.version>
        <spring-ai-agent-utils.version>0.10.0</spring-ai-agent-utils.version>
        <spring-ai-session.version>0.7.0</spring-ai-session.version>
        <spring-ai-mcp-security.version>0.1.13</spring-ai-mcp-security.version>
        <spring-ai-extensions.version>2.0.0-M1.1</spring-ai-extensions.version>
        <spring-ai-alibaba.version>2.0.0-M1.1</spring-ai-alibaba.version>
        <spring-boot.version>4.1.0</spring-boot.version>
        <spring-cloud.version>2025.1.2</spring-cloud.version>
        <spring-boot-admin.version>4.1.1</spring-boot-admin.version>
        <!-- ai -->
        <openai.version>4.41.0</openai.version>
        <dashscope.version>2.22.24</dashscope.version>
        <agent-scope.version>2.0.0</agent-scope.version>
        <!-- 3rd party -->
        <asm.version>9.10.1</asm.version>
        <cosid.version>3.2.0</cosid.version>
        <hutool.version>5.8.46</hutool.version>
        <guava.version>33.6.0-jre</guava.version>
        <netty.version>4.2.15.Final</netty.version>
        <playwright.version>1.60.0</playwright.version>
        <mybatis-plus.version>3.5.17</mybatis-plus.version>
        <shardingsphere.version>5.5.3</shardingsphere.version>
        <!-- tools -->
        <opentelemetry-semconv.version>1.42.0</opentelemetry-semconv.version>
        <!-- tools -->
        <lombok.version>1.18.46</lombok.version>
        <mapstruct.version>1.6.3</mapstruct.version>
        <lombok-mapstruct-binding.version>0.2.0</lombok-mapstruct-binding.version>
        <!-- webjars -->
        <layui.version>2.13.6</layui.version>
        <jquery.version>4.0.0</jquery.version>
        <popper.version>2.11.7</popper.version>
        <lodash.version>4.18.1</lodash.version>
        <marked.version>18.0.5</marked.version>
        <i18next.version>26.0.10</i18next.version>
        <bootstrap.version>5.3.8</bootstrap.version>
        <handlebars.version>4.7.7</handlebars.version>
        <font-awesome.version>7.2.0</font-awesome.version>
        <bootstrap-icons.version>1.13.1</bootstrap-icons.version>
        <i18next-http-backend.version>3.0.2</i18next-http-backend.version>
        <!-- maven -->
        <maven-war-plugin.version>3.5.1</maven-war-plugin.version>
        <maven-clean-plugin.version>3.5.0</maven-clean-plugin.version>
        <lombok-maven-plugin.version>1.18.20.0</lombok-maven-plugin.version>
        <maven-compiler-plugin.version>3.15.0</maven-compiler-plugin.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency><!-- spring-boot -->
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring-boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency><!-- spring-cloud -->
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency><!-- spring-boot-admin -->
                <groupId>de.codecentric</groupId>
                <artifactId>spring-boot-admin-dependencies</artifactId>
                <version>${spring-boot-admin.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency><!-- agentscope -->
                <groupId>io.agentscope</groupId>
                <artifactId>agentscope-bom</artifactId>
                <version>${agent-scope.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency><!-- cosid -->
                <groupId>me.ahoo.cosid</groupId>
                <artifactId>cosid-bom</artifactId>
                <version>${cosid.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency><!-- spring-ai -->
                <groupId>org.springframework.ai</groupId>
                <artifactId>spring-ai-bom</artifactId>
                <version>${spring-ai.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.springaicommunity</groupId>
                <artifactId>spring-ai-agent-utils-bom</artifactId>
                <version>${spring-ai-agent-utils.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.springaicommunity</groupId>
                <artifactId>spring-ai-session-bom</artifactId>
                <version>${spring-ai-session.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>com.alibaba.cloud.ai</groupId>
                <artifactId>spring-ai-alibaba-extensions-bom</artifactId>
                <version>${spring-ai-extensions.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>com.alibaba.cloud.ai</groupId>
                <artifactId>spring-ai-alibaba-bom</artifactId>
                <version>${spring-ai-alibaba.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.springaicommunity</groupId>
                <artifactId>mcp-server-security</artifactId>
                <version>${spring-ai-mcp-security.version}</version>
            </dependency>
            <dependency>
                <groupId>org.springaicommunity</groupId>
                <artifactId>mcp-server-security-spring-boot</artifactId>
                <version>${spring-ai-mcp-security.version}</version>
            </dependency>
            <dependency><!-- hutool -->
                <groupId>cn.hutool</groupId>
                <artifactId>hutool-bom</artifactId>
                <version>${hutool.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency><!-- mybatis-plus -->
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-bom</artifactId>
                <version>${mybatis-plus.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency><!-- netty -->
                <groupId>io.netty</groupId>
                <artifactId>netty-bom</artifactId>
                <version>${netty.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency><!-- shardingsphere -->
                <groupId>org.apache.shardingsphere</groupId>
                <artifactId>shardingsphere-jdbc</artifactId>
                <version>${shardingsphere.version}</version>
                <exclusions>
                    <exclusion>
                        <groupId>org.apache.shardingsphere</groupId>
                        <artifactId>shardingsphere-test-util</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>org.apache.shardingsphere</groupId>
                        <artifactId>shardingsphere-test-fixture-database</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency><!-- lombok -->
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
                <version>${lombok.version}</version>
            </dependency>
            <dependency><!-- mapstruct -->
                <groupId>org.mapstruct</groupId>
                <artifactId>mapstruct</artifactId>
                <version>${mapstruct.version}</version>
            </dependency>
            <dependency><!-- openai -->
                <groupId>com.openai</groupId>
                <artifactId>openai-java</artifactId>
                <version>${openai.version}</version>
            </dependency>
            <dependency>
                <groupId>com.openai</groupId>
                <artifactId>openai-java-core</artifactId>
                <version>${openai.version}</version>
            </dependency>
            <dependency><!-- dashscope -->
                <groupId>com.alibaba</groupId>
                <artifactId>dashscope-sdk-java</artifactId>
                <version>${dashscope.version}</version>
                <exclusions>
                    <exclusion>
                        <groupId>org.slf4j</groupId>
                        <artifactId>slf4j-simple</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency><!-- asm -->
                <groupId>org.ow2.asm</groupId>
                <artifactId>asm</artifactId>
                <version>${asm.version}</version>
            </dependency>
            <dependency><!-- guava -->
                <groupId>com.google.guava</groupId>
                <artifactId>guava</artifactId>
                <version>${guava.version}</version>
            </dependency>
            <dependency><!-- playwright -->
                <groupId>com.microsoft.playwright</groupId>
                <artifactId>playwright</artifactId>
                <version>${playwright.version}</version>
            </dependency>
            <!-- opentelemetry -->
            <dependency>
                <groupId>io.opentelemetry.semconv</groupId>
                <artifactId>opentelemetry-semconv</artifactId>
                <version>${opentelemetry-semconv.version}</version>
            </dependency>
            <!-- webjars -->
            <dependency>
                <groupId>org.webjars</groupId>
                <artifactId>jquery</artifactId>
                <version>${jquery.version}</version>
            </dependency>
            <dependency>
                <groupId>org.webjars</groupId>
                <artifactId>popper.js</artifactId>
                <version>${popper.version}</version>
            </dependency>
            <dependency>
                <groupId>org.webjars</groupId>
                <artifactId>bootstrap</artifactId>
                <version>${bootstrap.version}</version>
            </dependency>
            <dependency>
                <groupId>org.webjars</groupId>
                <artifactId>layui</artifactId>
                <version>${layui.version}</version>
            </dependency>
            <dependency>
                <groupId>org.webjars</groupId>
                <artifactId>handlebars</artifactId>
                <version>${handlebars.version}</version>
            </dependency>
            <dependency>
                <groupId>org.webjars</groupId>
                <artifactId>font-awesome</artifactId>
                <version>${font-awesome.version}</version>
            </dependency>
            <dependency>
                <groupId>org.webjars.npm</groupId>
                <artifactId>marked</artifactId>
                <version>${marked.version}</version>
            </dependency>
            <dependency>
                <groupId>org.webjars.npm</groupId>
                <artifactId>i18next</artifactId>
                <version>${i18next.version}</version>
            </dependency>
            <dependency>
                <groupId>org.webjars.npm</groupId>
                <artifactId>i18next-http-backend</artifactId>
                <version>${i18next-http-backend.version}</version>
            </dependency>
            <dependency>
                <groupId>org.webjars.npm</groupId>
                <artifactId>lodash</artifactId>
                <version>${lodash.version}</version>
            </dependency>
            <dependency>
                <groupId>org.webjars.npm</groupId>
                <artifactId>bootstrap-icons</artifactId>
                <version>${bootstrap-icons.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency><!-- lombok -->
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency><!-- mapstruct -->
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct</artifactId>
        </dependency>
        <dependency><!-- guava -->
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
        </dependency>
        <dependency><!-- hutool -->
            <groupId>cn.hutool</groupId>
            <artifactId>hutool-core</artifactId>
        </dependency>
    </dependencies>

    <build>
        <pluginManagement>
            <plugins>
                <plugin><!-- maven-compiler-plugin -->
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>${maven-compiler-plugin.version}</version>
                    <configuration>
                        <source>${project.source}</source>
                        <target>${project.target}</target>
                        <encoding>${project.encoding}</encoding>
                        <annotationProcessorPaths>
                            <path>
                                <groupId>org.mapstruct</groupId>
                                <artifactId>mapstruct-processor</artifactId>
                                <version>${mapstruct.version}</version>
                            </path>
                            <path>
                                <groupId>org.projectlombok</groupId>
                                <artifactId>lombok</artifactId>
                                <version>${lombok.version}</version>
                            </path>
                            <path>
                                <groupId>org.projectlombok</groupId>
                                <artifactId>lombok-mapstruct-binding</artifactId>
                                <version>${lombok-mapstruct-binding.version}</version>
                            </path>
                        </annotationProcessorPaths>
                    </configuration>
                </plugin>
                <plugin><!-- maven-war-plugin -->
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-war-plugin</artifactId>
                    <version>${maven-war-plugin.version}</version>
                    <configuration>
                        <failOnMissingWebXml>false</failOnMissingWebXml>
                    </configuration>
                </plugin>
                <plugin><!-- maven-clean-plugin -->
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-clean-plugin</artifactId>
                    <version>${maven-clean-plugin.version}</version>
                </plugin>
                <plugin><!-- lombok-maven-plugin -->
                    <groupId>org.projectlombok</groupId>
                    <artifactId>lombok-maven-plugin</artifactId>
                    <version>${lombok-maven-plugin.version}</version>
                </plugin>
                <plugin><!-- spring-boot-maven-plugin -->
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-maven-plugin</artifactId>
                    <version>${spring-boot.version}</version>
                </plugin>
            </plugins>
        </pluginManagement>

        <plugins>
            <plugin><!-- lombok-maven-plugin -->
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok-maven-plugin</artifactId>
            </plugin>
            <plugin><!-- maven-war-plugin -->
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-war-plugin</artifactId>
            </plugin>
            <plugin><!-- maven-clean-plugin -->
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-clean-plugin</artifactId>
            </plugin>
            <plugin><!-- spring-boot-maven-plugin -->
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>
